apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-123-test-rhtap-gitops
  description: This is GitOps manifest for py-123-test-rhtap   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py-123-test-rhtap
    janus-idp.io/tekton: py-123-test-rhtap
    backstage.io/kubernetes-id: py-123-test-rhtap 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-123-test-rhtap
