apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: py-123-test-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-123-test-rhtap 
  name: py-123-test-rhtap
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: py-123-test-rhtap
    weight: 100 
